services:
  front:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/ui:/code

  api:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
      - keycloak

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db-keycloak:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost # 重要
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - db-keycloak

  db-keycloak:
    image: postgres:17
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - keycloak-data:/var/lib/postgresql/data


volumes:
  db-data:
  keycloak-data:



